controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;
use app\models\User;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');
            return $this->refresh();
        }
		 $widgets =  \app\models\Widgetset::find()
			->where(['widgetset_id' =>3, 'widgetset.published'=>1])
			->innerJoinWith('widget')
			->orderBy('ordering')
			->asArray()
			->all();
        return $this->render('contact', [
            'model' => $model, 'widgets' => $widgets,
        ]);
    }

public function actionDelivery()
    {
		 $widgets =  \app\models\Widgetset::find()
			->where(['widgetset_id' =>3, 'widgetset.published'=>1])
			->innerJoinWith('widget')
			->orderBy('ordering')
			->asArray()
			->all();
        return $this->render('delivery', [
           'widgets' => $widgets,
        ]);
    }
	
	public function actionGuarantees()
    {
		 $widgets =  \app\models\Widgetset::find()
			->where(['widgetset_id' =>3, 'widgetset.published'=>1])
			->innerJoinWith('widget')
			->orderBy('ordering')
			->asArray()
			->all();
        return $this->render('guarantees', [
           'widgets' => $widgets,
        ]);
    }
}

views/site/about.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Html;

$this->title = 'About';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-about">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        This is the About page. You may modify the following file to customize its content:
    </p>

    <code><?= __FILE__ ?></code>
</div>

views/site/contact.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->params['widgets'] = \app\modules\shop\helpers\CookHtml::getWidget($widgets);
$this->title = 'Как с нами связаться:';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    <h1><?= Html::encode($this->title) ?></h1>

	<div class="col-md-4">
		<h3 class="title">Контакты:</h3>		
		<div class="media">
			<div class="media-left">
				<span class="glyphicon glyphicon-info-sign"></span>
			</div>
			<div class="media-body">
				<span class="contact-street">ООО "ИНФИНИТИ", ОГРН: 1147746223393</span>
			</div>
		</div>
		<div class="media">
			<div class="media-left">
				<span class="glyphicon glyphicon-home"></span>
			</div>
			<div class="media-body">
				<span class="contact-street">129515, г. Москва, ул. Хованская, 22, строение 1, офис 1 </span>
			</div>
		</div>
		<div class="media">
			<div class="media-left">
				<span class="glyphicon glyphicon-envelope"></span>
			</div>
			<div class="media-body">
				Почта: <a href="mailto:shop@vmela.ru">shop@vmela.ru</a>
			</div>
		</div>
		<div class="media">
			<div class="media-left">
				<span class="glyphicon glyphicon-earphone"></span>
			</div>
			<div class="media-body">
				Телефоны: 
				<ul class="list-unstyled">
					<li><strong>8-(800)-301-09-95</strong> Бесплатный по России</li>
					<li><strong>8-(495)-308-89-06</strong> по Москве и области</li>
					<li><strong>8-(495)-722-58-27</strong> по Москве и области</li>
				</ul>
			</div>
		</div>
		<div class="media">
			<div class="media-left">
				<span class="glyphicon glyphicon-calendar"></span>
			</div>
			<div class="media-body">
				<span>Часы работы: с 09:00 до 18:00  Без выходных.</span>
			</div>
			
			<div>
				<noindex>
				
<div class="col-xs-4" style="padding: 30px;"><a href="https://vkontakte.ru/vmela_ru" rel="nofollow" title="Мы ВКонтакте" target="_blank"><img src="https://image.freepik.com/free-icon/vk_318-136413.jpg"/></a></div>
   <div class="col-xs-4" style="padding: 30px;"> <a href="https://www.facebook.com/vmela_ru" rel="nofollow" title="Мы в Facebook" target="_blank"><img src="https://image.freepik.com/free-icon/facebook_318-136394.jpg"/></a></div>
   <div class="col-xs-4" style="padding: 30px;"> <a href="https://twitter.com/vmela_ru" rel="nofollow" title="Мы в Twitter" target="_blank"><img src="https://image.freepik.com/free-icon/twitter_318-136405.jpg"/></a></div>
</noindex>
			</div>
		</div>






	</div>
	<div class="col-sm-4">
		<h3 class="title">Сообщение с сайта:</h3>	
		<?php if (Yii::$app->session->hasFlash('contactFormSubmitted')): ?>

			<div class="alert alert-success">
				Благодарим Вас за обращение к нам. Мы ответим Вам как можно скорее.
			</div>

			<p>
				<?php if (Yii::$app->mailer->useFileTransport): ?>
					Because the application is in development mode, the email is not sent but saved as
					a file under <code><?= Yii::getAlias(Yii::$app->mailer->fileTransportPath) ?></code>.
					Please configure the <code>useFileTransport</code> property of the <code>mail</code>
					application component to be false to enable email sending.
				<?php endif; ?>
			</p>

		<?php else: ?>

			<p>Если у вас есть какие либо вопросы, заполните пожалуйста форму, чтобы связаться с нами.
				Спасибо!</p>

			<div class="row">
				<div class="col-lg-12">

					<?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

					<?= $form->field($model, 'name')->textInput(['autofocus' => true]) ?>

					<?= $form->field($model, 'email') ?>

					<?= $form->field($model, 'subject') ?>

					<?= $form->field($model, 'body')->textArea(['rows' => 6]) ?>

					<?=
					$form->field($model, 'verifyCode')->widget(Captcha::className(), [
						'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
					])
					?>

					<div class="form-group">
						<?= Html::submitButton('Submit', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
					</div>

					<?php ActiveForm::end(); ?>

				</div>
			</div>

		<?php endif; ?>
	</div>
	<div class="col-sm-4">
		<h3 class="title">Полезная информация:</h3>
		<p>
Полезные ссылки:</p>
		<ul class="list-unstyled">
			<li><i class="glyphicon glyphicon-paperclip"></i> <a href="">Информация о доставке</a></li>
			<li><i class="glyphicon glyphicon-paperclip"></i> <a href="">Условия обслуживания</a></li>
			<li><i class="glyphicon glyphicon-paperclip"></i> <a href="">Ваши заказы</a></li>
			<li><i class="glyphicon glyphicon-paperclip"></i> <a href="">Ваши данные</a></li>

		</ul>
		
	</div>
	<div class="clearfix"></div>
	
	
	<h3 class="title">Где мы находимся:</h3>
	<div class="map row">
<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=bZAaCWZQ2phc00zP0mVmgYWR3j7aLuv9&amp;width=100%25&amp;height=400&amp;lang=ru_RU&amp;sourceType=constructor&amp;scroll=true"></script>
</div>

views/site/delivery.php
<?php

use yii\helpers\Html;

$this->params['widgets'] = \app\modules\shop\helpers\CookHtml::getWidget($widgets);
$this->title = 'Подробности доставки:';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-delivery">
    <h1><?= Html::encode($this->title) ?></h1>

	<p class="jumbotron" style="font-size: 18px;">Доставка производится <strong>с 14:00 до 22:00 без выходных</strong>. В пределах МКАД Бесплатная доставка по себестоимости продукции от 80.000,00 руб. В некоторых случаях возможна срочная доставка в день заказа. <br><span style="color: #e92d00;">Обращаем также Ваше внимание</span> на то, что у нас нет жёстких временных рамок по доставке товара. Мы просто "разбиваем" день доставки на 2 интервала: дневной (условно с 14-ти до 18-ти часов) и вечерний (после 18-ти) для удобства наших покупателей. Если у Клиента есть конкретный и жёсткий временной отрезок, в который он может получить свой заказ, то это отдельно согласовывается с менеджером и ставится в известность службе доставки и курьеру, а также смещается "критическое" время доставки в меньшую сторону, чтобы не произошло нежелательных накладок.&nbsp;<span style="color: #e92d00;">Самовывоза временно нет.</span></p>
	<h3>Доставка по Москве:</h3>
	<p>Стоимость доставки телевизоров по Москве: <br>• размером до 42" дюймов - 490 рублей. <br>• размером от 42 " до 55" дюймов - 490 рублей. <br>• размером больше 55" дюймов - 490 рублей. <br>Стоимость доставки домашних кинотеатров, DVD-проигрывателей*, аксессуаров* <br>• 490 рублей.</p>
	<h3>Доставка в Подмосковье:</h3>
	<p>Стоимость доставки телевизоров в Подмосковье:</p>
	<ul><li>размером до 42" - 490 рублей + 30 руб. за каждый километр от МКАД.</li>
		<li>размером от 42" до 55" - 490 рублей +30 руб. за каждый км от МКАД.</li>
		<li>размером свыше 55" - 490 рублей +30 руб. за каждый км от МКАД.</li>
		<li>Стоимость доставки домашних кинотеатров, DVD-проигрывателей*, аксессуаров* 490 рублей + 30 руб. за каждый километр от МКАД.</li>
	</ul>
<p>* Если DVD-проигрыватель или аксессуары покупаются вместе с телевизором, или домашним кинотеатром, тогда оплачивается только доставка телевизора.</p>
	<p>Доставка оплачивается поштучно. Стоимость доставки каждого следующего товара (за исключением аксессуаров, кронштейнов, средств по уходу за техникой) в одном заказе составляет 50% от стоимости его доставки.</p>
	<p>Доставка не является неотъемлемой частью Товара. В случае отказа Покупателя от получения качественного Товара, соответствующего заказу и прилагаемым документам (номенклатура, количество, стоимость), Покупатель оплачивает стоимость его доставки.</p>
	<p >&nbsp;</p>
	<p>После заказа товар доставляется на следующий день с 14:00 до 22:00, но при необходимости вы можете получить его в тот же день. Сотрудники курьерской службы перед выездом к очередному покупателю связываются с ним по телефону, чтобы известить о времени своего прибытия. В процессе обработки заказа наш менеджер согласует с Вами параметры заказанных товаров и их стоимость. Сотрудники курьерской службы не производят работы по подключению, настройке и проверке доставляемой техники, а также не обучают основам правильной ее эксплуатации.</p>
	<p ><span style="color: #e92d00;">Обращаем также Ваше внимание</span> на то, что у нас нет жёстких временных рамок по доставке товара. Мы просто "разбиваем" день доставки на 2 интервала: дневной (условно с 14-ти до 18-ти часов) и вечерний (после 18-ти) для удобства наших покупателей. Если у Клиента есть конкретный и жёсткий временной отрезок, в который он может получить свой заказ, то это отдельно согласовывается с менеджером и ставится в известность службе доставки и курьеру, а также смещается "критическое" время доставки в меньшую сторону, чтобы не произошло нежелательных накладок.</p>
	<p>Доставка в регионы осуществляется по всей территории России транспортными компаниями "Деловые линии" или "ПЭК", или любой другой по выбору Покупателя, в соответствии с действующими тарифами, указанными на их сайте. Отправка заказа в другие города осуществляется по факту поступления средств на наш расчетный счет. Для точной и своевременной отправки Вашего заказа убедительно просим выслать на наш электронный адрес копию платежного документа или сообщить нам о факте оплаты по телефону. Отправка заказа производится после полной оплаты выставленного счета.</p>
	<h3 style="color: #ff3103; text-align: justify;">Оплата товара:</h3>
	<p style="text-align: justify;">При доставке заказа оплата принимается только в российских рублях, (наличными) строго в соответствии с ценой, указанной в товарном и/или кассовом чеке, которые Вы получаете вместе с товаром при доставке.</p>
	<h3 style="color: #ff3103; text-align: justify;">Безналичный расчет (для юр. лиц):</h3>
	<p style="text-align: justify;">По реквизитам Покупателя будет отправлен счёт на его электронный адрес после оформления заказа. Обращаем Ваше внимание на то, что к стоимости товара будет добавлено до 6% (необходимо уточнять у операторов). Все необходимые документы (оригинал счёта, счёт-фактура, товарно-траспортные накладные) Вы получаете вместе с товаром при доставке заказа.</p>
	<p>Смотрите также : <a href="<?= \yii\helpers\Url::to(['site/guarantees']) ?>">Возврат или обмен Товара</a></p>

</div>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/guarantees.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\ContactForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->params['widgets'] = \app\modules\shop\helpers\CookHtml::getWidget($widgets);
$this->title = 'Гарантии и условия возврата товара:';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-contact">
    


	<h3>ПОРЯДОК ВОЗВРАТА ТОВАРА</h3>
	<h4>1. Возврат или обмен Товара надлежащего качества.</h4>
	<ul class="unstyled" style="margin-left: 20px;">
		<li><strong>1.1 </strong>При дистанционной продаже, до передачи Товара Покупатель вправе отказаться от Товара в любое время, а после передачи Товара - в течение 7 (Семи) календарных дней.</li>
		<li>Возврат Товара надлежащего качества возможен в случае, если сохранены его товарный вид, потребительские свойства, а также документ, подтверждающий факт и условия покупки указанного Товара у Продавца. Отсутствие у Покупателя указанного документа не лишает его возможности ссылаться на другие доказательства приобретения Товара у данного Продавца.</li>
		<li><strong>1.2.</strong> Покупатель обязан выслать/передать в адрес Продавца Товар, от которого он отказался, в течение одного календарного дня после направления письменного требования Продавцу о возврате уплаченной стоимости Товара. При обоснованном отказе Покупателя от Товара Продавец возвращает ему сумму в размере стоимости Товара в течение 10 рабочих дней с даты с даты получения им письменного требования Покупателя о возврате стоимости Товара и самого Товара. Покупатель компенсирует Продавцу стоимость доставки Товара.</li>
		<li><strong>1.3.</strong> При отказе Покупателя от Товара надлежащего качества, Продавец по своему выбору производит возврат суммы, уплаченной Покупателем, с вычетом понесенных расходов, следующими способами:
			<ul>
				<li>наличными денежными средствами по месту нахождения Продавца;</li>
				<li>почтовым переводом;</li>
				<li>путем перечисления соответствующей суммы на банковский или иной счет покупателя, указанный покупателем.</li>
			</ul>
		</li>
		<li><strong>1.4.</strong> Если Товар надлежащего качества имеет индивидуально-определенные свойства и может быть использован исключительно приобретающим его Покупателем, то последний не вправе отказаться от указанного товара.</li>
		<li><strong>1.5.</strong> Возврат или обмен Товара надлежащего качества, поставляемого «под заказ», невозможен.</li>
	</ul>
	<h4>2. Возврат или обмен Товара ненадлежащего качества.</h4>
	<ul class="unstyled" style="margin-left: 20px;">
		<li><strong>2.1.</strong> Покупатель, которому продан Товар ненадлежащего качества, если это не было оговорено Продавцом в момент продажи Товара, и Покупателя данное условие устроило, вправе по своему выбору потребовать:
			<ul>
				<ul>
					<li>безвозмездного устранения недостатков Товара или возмещения расходов на их исправление Покупателем или третьим лицом;</li>
					<li>соразмерного уменьшения покупной цены;</li>
				</ul>
			</ul>
			<em>замены на Товар аналогичной марки (модели, артикула) или на такой же Товар другой марки (модели, артикула) с соответствующим перерасчетом покупной цены. При этом в отношении технически сложных и дорогостоящих Товаров эти требования Покупателя подлежат удовлетворению в случае обнаружения существенных недостатков.</em>
			<ul>
				<li>вправе отказаться от исполнения договора и потребовать возврата уплаченной за Товар суммы. По требованию Продавца и за его счет Покупатель должен возвратить Товар с недостатками.</li>
			</ul>
		</li>
		<li><strong>2.2.</strong> В отношении технически сложного Товара Покупатель в случае обнаружения в нем недостатков вправе отказаться от Товара и потребовать возврата уплаченной за такой Товар суммы либо предъявить требование о его замене на Товар этой же марки (модели, артикула) или на такой же Товар другой марки (модели, артикула) с соответствующим перерасчетом покупной цены в течение пятнадцати дней со дня передачи Покупателю такого Товара. По истечении этого срока указанные требования подлежат удовлетворению в одном из следующих случаев:
			<ul>
				<li>обнаружение существенного недостатка Товара;</li>
				<li>нарушение установленных Законом «О защите прав потребителей» сроков устранения недостатков Товара;</li>
				<li>невозможность использования Товара в течение каждого года гарантийного срока в совокупности более чем тридцать дней вследствие неоднократного устранения его различных недостатков.</li>
			</ul>
		</li>
		<li><strong>2.3.</strong> Основной срок для замены Товара, когда его недостатки очевидны, составляет 7 (семь) рабочих дней со дня предъявления письменного требования в адрес Продавца и обязательного предоставления Товара. Днем предъявления требования и получения Товара считается дата регистрации входящей корреспонденции и дата приема Продавцом Товара. В случае, если Продавец найдет необходимым провести дополнительную проверку Товара (с целью установления причин появления недостатков, установления вины Покупателя), Товар заменяется Продавцом в течение 20 (Двадцати) дней. Срок замены увеличивается, если на момент предъявления требования у Продавца необходимый Товар отсутствует.</li>
	</ul>
	<p><strong>3</strong>. При отказе Покупателя от Товара, при обоснованности заявленного требования, Продавец возвращает Покупателю денежную сумму, уплаченную Покупателем за Товар, за исключением расходов Продавца на доставку от Покупателя возвращенных Товаров, не позднее чем через десять дней со дня предъявления Покупателем соответствующего требования в случае отсутствия спора о наличии и причинах недостатка. Продавец имеет право провести проверку качества, либо экспертизу возвращаемого Товара. При отсутствии недостатка в Товаре и/или необоснованности требования о возврате Товара, устранения недостатка, Продавец вправе отказать в удовлетворении требования Покупателя.</p>
	<h3>ГАРАНТИИ НА ТОВАР И ОТВЕТСТВЕННОСТЬ</h3>
	<ul class="unstyled" style="margin-left: 20px;">
		<li><strong>1.</strong> Гарантийный срок эксплуатации на Товар устанавливает производитель (в случае, если это предусмотрено). Срок гарантии указывается в гарантийном талоне (в случае, если это предусмотрено). Продавец вправе установить на Товар гарантийный срок, если он не установлен изготовителем.</li>
		<li><strong>2.</strong> Продавец не несет ответственности за ущерб, причиненный Покупателю вследствие ненадлежащего использования приобретенного Товара.</li>
		<li><strong>3.</strong> Продавец не отвечает за убытки Покупателя, возникшие в результате:
			<ul>
				<li>неправильного заполнения Заказа, в т.ч. неправильного указания персональных данных;</li>
				<li>неправомерных действий третьих лиц;</li>
				<li>ненадлежащего использования Товара, как самим Покупателем, так и иными лицами.</li>
			</ul>
		</li>
		<li><strong>4.</strong> Покупатель несёт всю ответственность за достоверность сведений, указанных им при регистрации в Интернет - магазине.</li>
		<li><strong>5.</strong> Стороны освобождаются от ответственности за полное или частичное неисполнение своих обязательств, если такое неисполнение явилось следствием действия обстоятельств непреодолимой силы, возникших после вступления в силу настоящего Договора, в результате событий чрезвычайного характера, которые Стороны не могли предвидеть и предотвратить разумными мерами (Форс-мажор).</li>
		<li><strong>6.</strong> В течение срока гарантии Покупатель имеет право на бесплатный ремонт Товара, неисправность которого возникла по вине производителя.</li>
		<li><strong>7.</strong> За исключением гарантийных обязательств, указанных выше, Продавец не предоставляет никаких других гарантий, и в частности - по совместимости с какими-либо другими изделиями и программными продуктами третьих сторон.</li>
		<li><strong>8.</strong> Гарантийное обслуживание осуществляется в срок до сорока пяти дней, в зависимости от сложности ремонта и наличия запчастей.</li>
		<li><strong>9.</strong> Гарантийное обслуживание не осуществляется, а Продавец не несет гарантийных обязательств в следующих случаях:
			<ul>
				<ul>
					<li>если недостаток возник в результате механических повреждений или повреждений, вызванных несоблюдением требований хранения или эксплуатации Товара (следы ударов, трещины в корпусе, царапины, искривление корпуса из-за перегрева, следы попадания влаги, выдавливание жидкокристаллического дисплея, заливание клавиатуры различными жидкостями, деформация антенны, следы краски, клея и пр.), а также при ошибках и неверных действиях при подключении товара;</li>
					<li>в случае установления факта обслуживания товара лицами, не уполномоченными на проведение гарантийного обслуживания Товара;</li>
					<li>если недостаток возник вследствие естественного износа при эксплуатации Товара;</li>
					<li>если недостаток возник в результате изменения потребителем, или третьими лицами конструкции или схемы Товара, не предусмотренным изготовителем. В том числе из-за «разгона» или «перепрошивки» товара;</li>
					<li>если недостаток возник в результате воздействия непреодолимой силы, несчастными случаями, умышленными или неосторожными действиями (бездействием) потребителя или третьих лиц;</li>
					<li>если недостаток возник в результате воздействия влаги, высоких или низких температур, коррозией, окислением, попаданием внутрь Товара посторонних предметов, веществ, жидкостей, насекомых, следы от животных (покусы, погрызы, иные действия);</li>
					<li>при несоответствии серийного номера Товара с номером, указанным в гарантийном талоне.</li>
					<li>если недостаток возник в результате нестабильной электросети (скачки, завышенное или заниженное напряжение/ток);</li>
					<li>если недостаток возник в результате механических (трещины, сколы, вмятины, царапины и т.д.), электрических (разрыв конденсаторов, оплавления, подгоревшие микросхемы и т.д.) и термических (запах гари, копоть и т.д.) повреждений товара и/или деталей;</li>
					<li>если недостаток вызван воздействием вредоносных программ (вирусов, «троянов», «червей» и т.д.), нелицензионных программ, а так же иных программ, использование которых не гарантирует стабильную и/или безошибочную работу и Покупатель сам принимает решение об их использовании на свой страх и риск;</li>
				</ul>
			</ul>
			<em>если недостаток возник в результате использования Покупателем нестандартных и (или) некачественных расходных материалов, принадлежностей, запасных частей, элементов питания, носителей информации различных типов (включая, но, не ограничиваясь SIM-картами, картами памяти и т.д.);</em>
			<ul>
				<li>если недостаток возник в результате повреждения Товара, вызванного стихией, пожаром, бытовыми факторами.</li>
			</ul>
		</li>
		<li><strong>10.</strong> В случае невозможности Продавца осуществить гарантийное обслуживание Товара в установленный срок (сорок пять дней), в адрес Покупателя направляется уведомление с указанием причин неисполнения Договора в установленный срок, и, если Покупатель согласен на отсрочку исполнения обязательств, Продавец продолжает осуществление исполнения взятых на себя обязательств по гарантийному обслуживанию Товара. В случае отсутствия согласия Покупателя на увеличение сроков гарантийного обслуживания Товара Продавец по требованию Покупателя возвращает стоимость Товара.</li>
		<li><strong>11.</strong> Продавец не несет ответственности в случае неправильного выбора Покупателем характеристик или модификации Товара.</li>
	</ul> 
</div>

views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

    <?php $form = ActiveForm::begin([
        'id' => 'login-form',
        'options' => ['class' => 'form-horizontal'],
        'fieldConfig' => [
            'template' => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
            'labelOptions' => ['class' => 'col-lg-1 control-label'],
        ],
    ]); ?>

        <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <?= $form->field($model, 'rememberMe')->checkbox([
            'template' => "<div class=\"col-lg-offset-1 col-lg-3\">{input} {label}</div>\n<div class=\"col-lg-8\">{error}</div>",
        ]) ?>

        <div class="form-group">
            <div class="col-lg-offset-1 col-lg-11">
                <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
            </div>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="col-lg-offset-1" style="color:#999;">
        You may login with <strong>admin/admin</strong> or <strong>demo/demo</strong>.<br>
        To modify the username/password, please check out the code <code>app\models\User::$users</code>.
    </div>
</div>